name: Build

# Triggers on main branch pushes
on:
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install & build boost with components: python
      - name: Setup boost
        shell: cmd
        run: |
          git clone https://github.com/boostorg/boost.git
          cd boost
          git submodule update --init tools/boostdep
          git submodule update --init libs/python
          python tools/boostdep/depinst/depinst.py python
          bootstrap
      - name: Build boost
        shell: cmd
        run: |
          cd boost
          b2.exe --with-python
      # Build project using cmake
      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT=${{ github.workspace }}/boost ..
          cmake --build .

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install & build boost with components: python
      - name: Install boost
        shell: bash
        run: |
          git clone https://github.com/boostorg/boost.git
          cd boost
          git submodule update --init tools/boostdep
          git submodule update --init libs/python
          python tools/boostdep/depinst/depinst.py python
          ./bootstrap.sh
          ./b2 --with-python
      # Build project using cmake
      - name: Build project
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DBOOST_ROOT=${{ github.workspace }}/boost ..
          make
