name: Build

# Triggers on main branch pushes
on:
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install boost
      - name: Choco install boost
        shell: cmd
        run: |
          choco install boost-msvc-14.2
      # Build boost for installed python version
      - name: Build boost
        shell: cmd
        run: |
          cd C:\local\boost_*
          bootstrap
          .\b2 --with-python
      # Build project using cmake
      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 ..
          cmake --build .

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install boost
      - name: Apt install dependencies
        shell: cmd
        run: |
          sudo apt-get install libboost-all-dev
      # Build project using cmake
      - name: Build project
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake ..
          make
